### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by lschwall** [saanuregh/discord.js-pagination#31]
Running into a slight issue here.

Working with discord.js v12. Trying to work out a way to create pagination with > 25 fields for messageEmbedding. 

From what I can tell, I am sending the correct type to pagination, however it is coming back as undefined (which is not true).

My error I receive: 

```
(node:7328) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'send' of undefined
    at paginationEmbed (E:\myProjects\romanBot\node_modules\discord.js-pagination\index.js:6:36)
    at run (E:\myProjects\romanBot\bot\main.js:88:33)
    at E:\myProjects\romanBot\bot\main.js:101:29
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7328) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7328) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

From the DB I receive an `[{}]` in this format:
` [
  {
    id: 1,
    quote: 'hello',
    createdAt: '2021-07-04T15:31:32.571Z',
    updatedAt: '2021-07-04T15:31:32.571Z'
  }
  ]
`
Function to create pages: 
```
const run = async (message) => {
      const MAX_FIELDS = 25;
      // iterate over the commands and create field objects
      const fields = data.map(i => ({ name: i.id, value: i.quote }))

      // if there is less than 25 fields, you can safely send the embed
      // in a single message
      if (fields.length <= MAX_FIELDS)
          return message.reply(
              new Discord.MessageEmbed()
                  .setTitle('Help')
                  .setDescription(`Prefix: ${prefix}`)
                  .addFields(fields),
          );

      // if there are more, you need to create chunks w/ max 25 fields
      const chunks = chunkify(fields, MAX_FIELDS);
      // an array of embeds used by `discord.js-pagination`
      const pages = [];

      chunks.forEach((chunk) => {
          // create a new embed for each 25 fields
          pages.push(
              new Discord.MessageEmbed()
                  .setTitle('Help')
                  .setDescription(`Prefix: ${prefix}`)
                  .addFields(chunk),
          );
      });
      console.log('pages', pages)
      pagination('some message', pages);
  }
  function chunkify(arr, len) {
      let chunks = [];
      let i = 0;
      let n = arr.length;

      while (i < n) {
          chunks.push(arr.slice(i, (i += len)));
      }

      return chunks;
  }
  run(data);
```

When I console.log(pages) before initializing `pagination('some message', pages)`, I recieve: 

```
pages [
  MessageEmbed {
    type: 'rich',
    title: 'Help',
    description: 'Prefix: !',
    url: null,
    color: null,
    timestamp: null,
    fields: [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object]
    ],
    thumbnail: null,
    image: null,
    video: null,
    author: null,
    provider: null,
    footer: null,
    files: []
  },
  MessageEmbed {
    type: 'rich',
    title: 'Help',
    description: 'Prefix: !',
    url: null,
    color: null,
    timestamp: null,
    fields: [ [Object], [Object] ],
    thumbnail: null,
    image: null,
    video: null,
    author: null,
    provider: null,
    footer: null,
    files: []
  }
]

```
My misunderstanding comes to play when trying to assess what the pagination package is supposed to accept. It seems to be wanting an array of objects/arrays. Which is what I am sending. 

Any help would be appreciated.

**Comment by lschwall** [comment]
Was solved by changing  `pagination('some message', pages);` to `pagination(msg, pages);`. Without the actual message, discord-js-pagination cannot solve the promise of sending to the message's channel.
