### ISSUE TITLE
Test error: DiscordAPIError: Invalid Webhook Token

### ISSUE THREAD

**Issue by Xeinel** [saanuregh/discord.js-pagination#43]
Hi, since today, when I use button I have the following error :

Test error: DiscordAPIError: Invalid Webhook Token
    at RequestHandler.execute (c:\Users\paulg\OneDrive\Documents\GitHub\XeinMod\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at process.processTicksAndRejections (c:\Users\paulg\OneDrive\Documents\GitHub\XeinMod\lib\internal\process\task_queues.js:95:5)
    at async RequestHandler.push (c:\Users\paulg\OneDrive\Documents\GitHub\XeinMod\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async InteractionWebhook.editMessage (c:\Users\paulg\OneDrive\Documents\GitHub\XeinMod\node_modules\discord.js\src\structures\Webhook.js:325:15)
    at async ButtonInteraction.editReply (c:\Users\paulg\OneDrive\Documents\GitHub\XeinMod\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:139:21)
    at async InteractionCollector.<anonymous> (c:\Users\paulg\OneDrive\Documents\GitHub\XeinMod\node_modules\discordjs-button-pagination\index.js:55:5) {name: 'DiscordAPIError', message: 'Invalid Webhook Token', method: 'patch', path: '/webhooks/972468572045602816/aW50ZXJhY3Rpb246M…d0ZuZ1R6T3ppQ2VocWVzYm9KRw/messages/@original', code: 50027, …}
    
    I do not change anything in the file but I have this error since this afternoon.
    You can contact me on discord : Xeinel#7030
    
    Thank you

**Comment by lilmistake** [comment]
This was a known Discord API error, it was fixed within a few hours. https://github.com/discordjs/discord.js/issues/8335

**Comment by Xeinel** [comment]
Yes I have just seen that a few minuts after :D 
Thank you
